### PR TITLE
Minor updates on foundry config 

### PR DESCRIPTION
**Pull request by kootsZhin**
- change `default` to `profile.default` in `foundry.toml`
- change to use `forge install` in README
- add remappings

### CODE REVIEW

**Comment by dmfxyz** [comment]
Thanks -- looks good. Let me just fix the slither workflow so that it runs before we merge this.

**Comment by dmfxyz** [comment]
@kootsZhin merge main when you get a chance

**Comment by kootsZhin** [comment]
> @kootsZhin merge upstream main when you get a chance

done!

**Review by dmfxyz — APPROVED** [review]
LGTM! Thank you.

**Pull request merged**
